# Generated by Django 5.2.6 on 2025-09-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.CharField(blank=True, max_length=200)),
                ('stock', models.PositiveIntegerField(default=10)),
                ('tag', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
